services:
  sce-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: sce-app
    environment:
      APP_ENV:           ${APP_ENV:-production}
      APP_DEBUG:         "false"
      LOG_CHANNEL:       stderr
      APP_KEY:           ${APP_KEY:-base64:tncjk6Htau/rVmmx9lc8MMJ8mqjLhOVYqjBaSoyvzwg=}

      # Database → point to your external service
      DB_CONNECTION:     mysql
      DB_HOST:           ${DB_HOST:-db2.kevinchr.com} 
      DB_PORT:           ${DB_PORT:-3306}
      DB_DATABASE:       ${DB_DATABASE:-studentcouncilelection}
      DB_USERNAME:       ${DB_USERNAME:-studentcouncilelection}
      DB_PASSWORD:       ${DB_PASSWORD:-ACCESS!def00}
    volumes:
      - drive_2:/var/www/
    networks:
      - sce-net
    expose:
      - "9000"

    
  sce-web:
    build: ./nginx
    depends_on:
      - sce-app
    restart: always
    container_name: sce-web
    volumes:
      - drive_2:/var/www/
    expose:
      - "80"                              # HTTP for NPM

    networks:
      - sce-net                           # to reach sce:9000
      - link0                             # external network NPM uses

volumes:
  drive_2:

networks:
  sce-net:
  link0:
    external: true
